=== bahungbnck99/app-runtime-assets/schemas/asset-pack.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/bahungbnck99/app-runtime-assets/main/schemas/asset-pack.schema.json",
  "type": "object",
  "required": [
    "schemaVersion",
    "assetType",
    "version",
    "installMode",
    "items"
  ],
  "properties": {
    "schemaVersion": {
      "const": 1
    },
    "assetType": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "channel": {
      "type": "string"
    },
    "installMode": {
      "enum": [
        "zip"
      ]
    },
    "packUrl": {
      "type": "string"
    },
    "packSha256": {
      "type": "string"
    },
    "installDir": {
      "type": "string"
    },
    "apps": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "items": {
      "type": "array"
    }
  }
}

=== bahungbnck99/app-runtime-assets/manifests/fonts.json
{
    "schemaVersion":  1,
    "assetType":  "fonts",
    "version":  "2026.06.26",
    "channel":  "stable",
    "installMode":  "zip",
    "packUrl":  "https://raw.githubusercontent.com/bahungbnck99/app-runtime-assets/main/packs/fonts/fonts-pack-2026.06.26.zip",
    "packSha256":  "8e427e1f786195cb5e0a74571e33b3979773b89e5045e7274473a797d5a5dfdf",
    "installDir":  "fonts",
    "apps":  [
                 "download-multi-platform",
                 "*"
             ],
    "items":  [
                  {
                      "id":  "vhantiq",
                      "family":  "VHANTIQ",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHANTIQ.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vharabia",
                      "family":  "VHARABIA",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHARABIA.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhariabi",
                      "family":  "VHARIABI",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHARIABI.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vharial",
                      "family":  "VHARIAL",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHARIAL.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vharialb",
                      "family":  "VHARIALB",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHARIALB.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhariali",
                      "family":  "VHARIALI",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHARIALI.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vharialn",
                      "family":  "VHARIALN",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHARIALN.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vharis",
                      "family":  "VHARIS",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHARIS.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhavan",
                      "family":  "VHAVAN",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHAVAN.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhavanb",
                      "family":  "VHAVANB",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHAVANB.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhavanbi",
                      "family":  "VHAVANBI",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHAVANBI.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhavani",
                      "family":  "VHAVANI",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHAVANI.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhbahab",
                      "family":  "VHBAHAB",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHBAHAB.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhblack",
                      "family":  "VH",
                      "weight":  900,
                      "style":  "normal",
                      "file":  "fonts/VHBLACK.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhbodo",
                      "family":  "VHBODO",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHBODO.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhcentb",
                      "family":  "VHCENTB",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHCENTB.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhcentbi",
                      "family":  "VHCENTBI",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHCENTBI.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhcenti",
                      "family":  "VHCENTI",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHCENTI.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhcentn",
                      "family":  "VHCENTN",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHCENTN.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhclare",
                      "family":  "VHCLARE",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHCLARE.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhcomsci",
                      "family":  "VHCOMSCI",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHCOMSCI.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhcoop",
                      "family":  "VHCOOP",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHCOOP.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhcorvi",
                      "family":  "VHCORVI",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHCORVI.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhcour",
                      "family":  "VHCOUR",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHCOUR.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhcourb",
                      "family":  "VHCOURB",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHCOURB.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhelvcn",
                      "family":  "VHELVCN",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHELVCN.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhelveb",
                      "family":  "VHELVEB",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHELVEB.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhelvebi",
                      "family":  "VHELVEBI",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHELVEBI.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhelvei",
                      "family":  "VHELVEI",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHELVEI.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhelven",
                      "family":  "VHELVEN",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHELVEN.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhexotic",
                      "family":  "VHEXOTIC",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHEXOTIC.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhfree",
                      "family":  "VHFREE",
                      "weight":  400,
                      "style":  "normal",
                      "file":  "fonts/VHFREE.TTF",
                      "license":  ""
                  },
                  {
                      "id":  "vhgoth",
